#!/usr/bin/env python

Import("env")
Import("env_modules")

env_gdextension_test = env_modules.Clone()
module_obj = []
env_gdextension_test.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj
